insert into USER_(ID,CREATE_DATE,USER_NAME) VALUES
    (1,CURRENT_TIMESTAMP ,'bambam')
    ,(2 ,CURRENT_TIMESTAMP ,'bambam_2')
    ,(3,CURRENT_TIMESTAMP ,'bambam_3');

insert into USER_MATCH("CREATE_DATE","APP_ACTION","SCORE","USER_ACTION","USER_ID")
VALUES  (CURRENT_TIMESTAMP,'PAPER',1,'SCISSOR',1)
        ,(CURRENT_TIMESTAMP,'PAPER',1,'SCISSOR',1)
        ,(CURRENT_TIMESTAMP,'PAPER',1,'SCISSOR',1)
        ,(CURRENT_TIMESTAMP,'ROCK',-1,'SCISSOR',1)
        ,(CURRENT_TIMESTAMP,'ROCK',0,'ROCK',1)

        ,(CURRENT_TIMESTAMP,'PAPER',1,'SCISSOR',2)
        ,(CURRENT_TIMESTAMP,'PAPER',1,'SCISSOR',2)
        ,(CURRENT_TIMESTAMP,'PAPER',1,'SCISSOR',2)
        ,(CURRENT_TIMESTAMP,'ROCK',-1,'SCISSOR',3)
        ,(CURRENT_TIMESTAMP,'ROCK',0,'ROCK',3);